name: New template

on:
  push:
    branches:
      - master

jobs:
  update-with-new-template:
    if: "contains(github.event.head_commit.message, '[new_template]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Append to README.md
        env: 
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          TEMPLATE_NAME=${COMMIT_MESSAGE#*new_template }
          TEMPLATE_NAME=${TEMPLATE_NAME%% *}
          
          echo "| $TEMPLATE_NAME | [$TEMPLATE_NAME]($TEMPLATE_NAME) | [README]($TEMPLATE_NAME/README.md) | " >> README.md

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3 
        with:
          ref: ${{ github.head_ref }}
          prettier_options: --write README.md

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: '[actions] Update README.md with new template'
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: |
            - README.md
